name: SSH to Cloudflare tunnels

on:
  push:
    branches:
      - main

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Setup cloudflared
        run: |
          mkdir -p --mode=0755 /usr/share/keyrings
          curl -fsSL https://pkg.cloudflare.com/cloudflare-main.gpg | tee /usr/share/keyrings/cloudflare-main.gpg >/dev/null
          echo 'deb [signed-by=/usr/share/keyrings/cloudflare-main.gpg] https://pkg.cloudflare.com/cloudflared jammy main' | tee /etc/apt/sources.list.d/cloudflared.list
          apt-get update && apt-get install cloudflared

      - name: Update SSH Config file
        run: |
          echo "Host ${{ secrets.HOST }}" >> ~/.ssh/config
          echo "ProxyCommand /usr/local/bin/cloudflared access ssh --hostname %h" >> ~/.ssh/config

      - name: Execute SSH Command
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script_stop: true
          script: |
            ls
            whoami
